[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18"

# Next.js 정적 사이트를 위한 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000 