[build]
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"

# Next.js 리다이렉트 처리
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000 